[build]
builder = "Nixpacks"

[build.env]
PYTHON_VERSION = "3.10"  # Adjust if necessary

[build.dependencies]
apt = ["libgl1", "libglib2.0-0"]  # Install OpenCV dependencies

[start]
cmd = "gunicorn app:app"
